version: '2'

services:
  sh72:
    build:
      context: .docker/php@7.2/cli
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"

  sh72-xdebug:
    build:
      context: .docker/php@7.2/cli-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.2/cli-xdebug/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./:/var/www/html
    restart: "no"

  sh74:
    build:
      context: .docker/php@7.4/cli
    user: docker:docker
    volumes:
      - ./.docker/php@7.4/cli/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./:/var/www/html
    restart: "no"

  sh74-xdebug:
    build:
      context: .docker/php@7.4/cli-xdebug
    user: docker:docker
    volumes:
      - ./.docker/php@7.4/cli-xdebug/config/memory.ini:/usr/local/etc/php/conf.d/memory.ini:ro
      - ./.docker/php@7.2/cli-xdebug/config/security.ini:/usr/local/etc/php/conf.d/security.ini:ro
      - ./.docker/php@7.4/cli-xdebug/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
      - ./:/var/www/html
    restart: "no"

  composer:
    extends:
      service: composer74

  composer72:
    extends:
      service: sh72
    environment:
      COMPOSER_AUTH: >
        {"github-oauth":{"github.com": "${COMPOSER_GITHUB_TOKEN}"}}
    entrypoint: [ "composer" ]
    restart: "no"

  composer74:
    extends:
      service: sh74
    environment:
      COMPOSER_AUTH: >
        {"github-oauth":{"github.com": "${COMPOSER_GITHUB_TOKEN}"}}
    entrypoint: [ "composer" ]
    restart: "no"

  phpunit:
    extends:
      service: phpunit74-xdebug

  phpunit72:
    extends:
      service: sh72
    entrypoint: [ "vendor/bin/phpunit", "--configuration=.phpunit.xml" ]
    restart: "no"

  phpunit72-xdebug:
    extends:
      service: sh72-xdebug
    entrypoint: [ "vendor/bin/phpunit", "--configuration=.phpunit.xml" ]
    restart: "no"

  phpunit74:
    extends:
      service: sh74
    entrypoint: [ "vendor/bin/phpunit", "--configuration=.phpunit.xml" ]
    restart: "no"

  phpunit74-xdebug:
    extends:
      service: sh74-xdebug
    entrypoint: [ "vendor/bin/phpunit", "--configuration=.phpunit.xml" ]
    restart: "no"

  phpspec:
    extends:
      service: phpspec74-xdebug

  phpspec72:
    extends:
      service: sh72
    entrypoint: [ "vendor/bin/phpspec" ]
    restart: "no"

  phpspec72-xdebug:
    extends:
      service: sh72-xdebug
    entrypoint: [ "vendor/bin/phpspec" ]
    restart: "no"

  phpspec74:
    extends:
      service: sh74
    entrypoint: [ "vendor/bin/phpspec" ]
    restart: "no"

  phpspec74-xdebug:
    extends:
      service: sh74-xdebug
    entrypoint: [ "vendor/bin/phpspec" ]
    restart: "no"

  phpstan:
    extends:
      service: phpstan74

  phpstan72:
    extends:
      service: sh72
    entrypoint: [ "vendor/bin/phpstan" ]
    restart: "no"

  phpstan74:
    extends:
      service: sh74
    entrypoint: [ "vendor/bin/phpstan" ]
    restart: "no"
